import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

// Shared quiz-results report - used by both Present.tsx (teacher) and
// AudienceJoin.tsx (students) so everyone downloads the exact same styled
// report. Renders as real (off-screen) HTML, then html2canvas rasterizes
// it - one capture feeds both the PNG and the PDF exports, so they always
// match pixel-for-pixel.

export interface ReportQuestion {
  id: string;
  question: string;
  correctText: string;
  source?: string;
  correctCount: number;
  incorrectCount: number;
}
export interface ReportParticipant {
  rank: number;
  name: string;
  emoji: string;
  score: number;
  correctCount: number;
  totalQuestions: number;
}
export interface QuizReportData {
  title: string;
  dateLabel: string;
  leaderboard: ReportParticipant[];
  questions: ReportQuestion[];
}

const MEDALS = ['🥇', '🥈', '🥉'];

export function QuizReportCard({ data }: { data: QuizReportData }) {
  return (
    <div
      style={{
        width: 794, // ~A4 at 96dpi
        background: '#0b1020',
        color: '#fff',
        fontFamily: "'Segoe UI', Tahoma, Arial, sans-serif",
        padding: 0,
      }}
    >
      <div style={{ background: 'linear-gradient(135deg, #4338ca 0%, #7c3aed 50%, #db2777 100%)', padding: '40px 48px' }}>
        <p style={{ margin: 0, fontSize: 13, letterSpacing: 2, opacity: 0.85, textTransform: 'uppercase' }}>Remco · Quiz Results</p>
        <h1 style={{ margin: '8px 0 0', fontSize: 34, fontWeight: 800 }}>{data.title}</h1>
        <p style={{ margin: '6px 0 0', fontSize: 13, opacity: 0.85 }}>{data.dateLabel}</p>
      </div>

      <div style={{ padding: '32px 48px' }}>
        <h2 style={{ fontSize: 18, fontWeight: 700, margin: '0 0 14px', color: '#fbbf24' }}>🏆 Leaderboard</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 36 }}>
          {data.leaderboard.map((p) => (
            <div
              key={p.rank}
              style={{
                display: 'flex', alignItems: 'center', gap: 14, padding: '12px 16px', borderRadius: 12,
                background: p.rank === 1 ? 'linear-gradient(90deg, rgba(251,191,36,0.25), rgba(251,191,36,0.05))' : 'rgba(255,255,255,0.06)',
                border: p.rank <= 3 ? '1px solid rgba(251,191,36,0.4)' : '1px solid rgba(255,255,255,0.08)',
              }}
            >
              <span style={{ fontSize: 22, width: 34, textAlign: 'center' }}>{MEDALS[p.rank - 1] || `#${p.rank}`}</span>
              <span style={{ fontSize: 20 }}>{p.emoji}</span>
              <span style={{ flex: 1, fontSize: 16, fontWeight: 600 }}>{p.name}</span>
              <span style={{ fontSize: 13, opacity: 0.7 }}>{p.correctCount}/{p.totalQuestions} correct</span>
              <span style={{ fontSize: 18, fontWeight: 800, width: 70, textAlign: 'right', fontVariantNumeric: 'tabular-nums' }}>{p.score}</span>
            </div>
          ))}
          {data.leaderboard.length === 0 && <p style={{ opacity: 0.6, fontSize: 14 }}>No participants.</p>}
        </div>

        <h2 style={{ fontSize: 18, fontWeight: 700, margin: '0 0 14px', color: '#60a5fa' }}>📋 Questions</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          {data.questions.map((q, i) => (
            <div key={q.id} style={{ background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 12, padding: '16px 18px' }}>
              <p style={{ margin: 0, fontSize: 15, fontWeight: 700 }}>{i + 1}. {q.question}</p>
              <p style={{ margin: '8px 0 0', fontSize: 13.5 }}>
                <span style={{ color: '#34d399', fontWeight: 700 }}>✓ Correct answer:</span> {q.correctText}
              </p>
              <div style={{ display: 'flex', gap: 16, marginTop: 8, fontSize: 12.5, opacity: 0.85 }}>
                <span style={{ color: '#34d399' }}>✓ {q.correctCount} correct</span>
                <span style={{ color: '#f87171' }}>✕ {q.incorrectCount} incorrect</span>
              </div>
              {q.source && (
                <p style={{ margin: '10px 0 0', fontSize: 12.5, color: '#a5b4fc', borderTop: '1px dashed rgba(255,255,255,0.15)', paddingTop: 8 }}>
                  📚 Source: {q.source}
                </p>
              )}
            </div>
          ))}
          {data.questions.length === 0 && <p style={{ opacity: 0.6, fontSize: 14 }}>No questions.</p>}
        </div>

        <p style={{ marginTop: 36, fontSize: 11, opacity: 0.4, textAlign: 'center' }}>Generated by Remco</p>
      </div>
    </div>
  );
}

// Captures an off-screen-rendered report node (see the -9999px positioning
// pattern used by callers) and produces a PNG download.
export async function exportReportPNG(node: HTMLElement, filename: string) {
  const canvas = await html2canvas(node, { backgroundColor: '#0b1020', scale: 2, useCORS: true });
  const blob: Blob | null = await new Promise((resolve) => canvas.toBlob(resolve, 'image/png'));
  if (!blob) return;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

// Same capture, sliced across as many A4 pages as needed and dropped into a PDF.
export async function exportReportPDF(node: HTMLElement, filename: string) {
  const canvas = await html2canvas(node, { backgroundColor: '#0b1020', scale: 2, useCORS: true });
  const pdf = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const imgWidth = pageWidth;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  if (imgHeight <= pageHeight) {
    pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0, imgWidth, imgHeight);
  } else {
    // Slice the tall canvas into page-height chunks so long leaderboards /
    // question lists flow onto additional pages instead of getting cut off.
    const pxPerPage = Math.floor((pageHeight * canvas.width) / imgWidth);
    let renderedPx = 0;
    let first = true;
    while (renderedPx < canvas.height) {
      const sliceHeight = Math.min(pxPerPage, canvas.height - renderedPx);
      const pageCanvas = document.createElement('canvas');
      pageCanvas.width = canvas.width;
      pageCanvas.height = sliceHeight;
      const ctx = pageCanvas.getContext('2d');
      if (ctx) {
        ctx.fillStyle = '#0b1020';
        ctx.fillRect(0, 0, pageCanvas.width, pageCanvas.height);
        ctx.drawImage(canvas, 0, renderedPx, canvas.width, sliceHeight, 0, 0, canvas.width, sliceHeight);
      }
      if (!first) pdf.addPage();
      pdf.addImage(pageCanvas.toDataURL('image/png'), 'PNG', 0, 0, imgWidth, (sliceHeight * imgWidth) / canvas.width);
      renderedPx += sliceHeight;
      first = false;
    }
  }
  pdf.save(filename);
}
